name: Fullstack Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'src/frontend/**'
      - 'src/backend/**'
      - 'Dockerfile'

env:
  REGION: us-east1
  SERVICE_NAME: term-deposit-fullstack
  REPOSITORY: term-deposit-docker-repo
  IMAGE_NAME: term-deposit-app
  IMAGE_URI: us-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/term-deposit-docker-repo/term-deposit-app

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker us-east1-docker.pkg.dev

      - name: Build Docker image
        run: docker build -t ${{ env.IMAGE_URI }}:${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker push ${{ env.IMAGE_URI }}:${{ github.sha }}
          docker tag ${{ env.IMAGE_URI }}:${{ github.sha }} ${{ env.IMAGE_URI }}:latest
          docker push ${{ env.IMAGE_URI }}:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image=${{ env.IMAGE_URI }}:${{ github.sha }} \
            --platform=managed \
            --region=${{ env.REGION }} \
            --allow-unauthenticated \
            --project=${{ secrets.GCP_PROJECT_ID }}
