name: Setup GCP VM for Airflow

on:
  workflow_dispatch:

jobs:
  create-vm:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Authenticate with GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: readmission-prediction-452220

    - name: Verify GCP authentication
      run: |
        gcloud auth list
        gcloud config list
        gcloud compute zones list --limit=1

    - name: Enable Compute Engine API
      run: |
        gcloud services enable compute.googleapis.com

    - name: Create GCP VM instance
      run: |
        gcloud compute instances create airflow-vm \
          --zone=us-central1-a \
          --machine-type=e2-micro \
          --image-family=debian-11 \
          --image-project=debian-cloud \
          --boot-disk-size=20GB \
          --tags=http-server,https-server \
          --metadata=startup-script='#! /bin/bash
            sudo apt-get update
            sudo apt-get install -y python3 python3-pip
            curl -fsSL https://get.docker.com -o get-docker.sh
            sh get-docker.sh
            sudo usermod -aG docker $USER
            newgrp docker
          '

    - name: Output External IP
      run: |
        gcloud compute instances describe airflow-vm \
          --zone=us-central1-a \
          --format='get(networkInterfaces[0].accessConfigs[0].natIP)'
